name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make build
        env:
          VERSION: latest
      - name: Test
        run: make test
      - name: Lint
        run: make lint
  
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: ci
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'

      - name: Build
        run: make build
        env:
          VERSION: ${{ steps.version.outputs.value}}

      - name: Deploy
        run: |
          make push

          git config --global user.name 'Github Actions'
          git config --global user.email 'system@fennelmarkets.com'
          
          git tag -d v1 && git push --delete origin v1
          git tag ${VERSION} && git tag v1 && git push origin --tags
        env:
          VERSION: ${{ steps.version.outputs.value}}
